import utcToZonedTime from 'date-fns-tz/utcToZonedTime';
import format from 'date-fns/format';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

const useCurrentTime = () => {
    const [currentTime, setCurrentTime] = useState(new Date());
    useEffect(() => {
        const timer = setInterval(() => {
            setCurrentTime(new Date());
        }, 1000);
        return () => clearInterval(timer);
    }, []);
    return currentTime;
};

const useTimeInZone = () => {
    const currentTime = useCurrentTime();
    return utcToZonedTime(currentTime, 'America/Los_Angeles');
};

const Home: NextPage = () => {
    const currentTime = useCurrentTime();
    const timeInLa = useTimeInZone();
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="h-screen grid place-items-center">
                <div className="big-shadow w-[90%] h-[90%]  md:w-[600px] md:h-[400px] border border-[#C9C9C9]/30 rounded-3xl shadow-2xl flex flex-col justify-center">
                    <div className="mx-auto my-6 text-xl">
                        {format(currentTime, 'K:mm:ss a')}
                    </div>
                    <div className="border-t-[#C9C9C9]/30 w-[80%] border-t mx-auto"></div>
                    <div className="mx-auto my-6 text-xl">
                        {format(timeInLa, 'K:mm:ss a')}
                    </div>
                </div>
            </div>
        </>
    );
};

export default Home;
